In [1]:
using CSV, DataFrames, Dates
using FileIO
# using LaTeXStrings

In [2]:
romania_full = CSV.read("../data/romania.csv", DataFrame);
romania = romania_full[romania_full.Datetime .> DateTime(1976,1,1,0,0,0),:]

31383×5 DataFrame
   Row │ Datetime                 Latitude  Longitude  Depth    Magnitude 
       │ DateTime                 Float64   Float64    Float64  Float64   
───────┼──────────────────────────────────────────────────────────────────
     1 │ 1976-02-03T13:29:16.400   45.32      25.99      184.3        2.6
     2 │ 1976-08-19T19:03:00.800   45.54      26.37      162.0        2.3
     3 │ 1976-09-07T17:38:08.200   45.62      26.5       155.3        3.6
     4 │ 1976-10-01T17:50:43.200   45.68      26.49      146.0        6.0
     5 │ 1976-10-15T10:54:48       47.1       25.6        17.0        3.9
     6 │ 1977-03-04T19:21:54.100   45.77      26.76       94.0        7.4
     7 │ 1977-03-04T21:21:01.100   45.22      26.65      141.0        3.0
     8 │ 1977-03-04T21:28:07.400   45.23      26.87       22.0        1.5
   ⋮   │            ⋮                ⋮          ⋮         ⋮         ⋮
 31377 │ 2022-12-29T09:28:11.270   45.2972    25.093       2.0        1.5
 31378 │ 2022-12-29T09:42:33.920   45.9596    22.6972      3.3        1.6
 31379 │ 2022-12-29T12:16:03.080   46.3226    23.1438      1.0        1.7
 31380 │ 2022-12-29T13:11:43.570   45.4378    24.1116     11.7        2.1
 31381 │ 2022-12-30T14:23:49.390   45.4639    24.1433     14.0        1.7
 31382 │ 2022-12-31T03:16:48.320   45.4082    24.134      18.2        1.7
 31383 │ 2022-12-31T15:24:39.550   45.0022    22.6597      4.5        2.1
                                                        31368 rows omitted

In [6]:
vrancea = romania[(romania.Latitude .>= 45.20) .& (romania.Latitude .<= 46.0) .& 
                    (romania.Longitude .>= 26.0) .& (romania.Longitude .<= 27.0) .&
                    (romania.Depth .>= 50.0) .& (romania.Depth .<= 200.0), :]

7890×5 DataFrame
  Row │ Datetime                 Latitude  Longitude  Depth    Magnitude 
      │ DateTime                 Float64   Float64    Float64  Float64   
──────┼──────────────────────────────────────────────────────────────────
    1 │ 1976-08-19T19:03:00.800   45.54      26.37      162.0        2.3
    2 │ 1976-09-07T17:38:08.200   45.62      26.5       155.3        3.6
    3 │ 1976-10-01T17:50:43.200   45.68      26.49      146.0        6.0
    4 │ 1977-03-04T19:21:54.100   45.77      26.76       94.0        7.4
    5 │ 1977-03-04T21:21:01.100   45.22      26.65      141.0        3.0
    6 │ 1977-03-05T02:35:22       45.63      26.19      121.3        3.0
    7 │ 1977-03-05T12:08:42       45.37      26.3       124.0        3.5
    8 │ 1977-03-06T13:27:06.300   45.83      26.63      112.3        2.6
  ⋮   │            ⋮                ⋮          ⋮         ⋮         ⋮
 7884 │ 2022-12-17T05:42:58.120   45.641     26.487     143.8        4.1
 7885 │ 2022-12-18T03:23:22.420   45.7235    26.6176    138.4        2.7
 7886 │ 2022-12-19T19:32:11.030   45.7157    26.6342     85.7        2.7
 7887 │ 2022-12-26T07:47:10.270   45.5403    26.5114    105.9        3.5
 7888 │ 2022-12-27T16:00:52.890   45.5211    26.4184    110.2        2.5
 7889 │ 2022-12-28T07:38:54.270   45.7505    26.6086     85.2        2.9
 7890 │ 2022-12-29T02:06:28.320   45.6714    26.6291    134.0        2.8
                                                        7875 rows omitted

In [11]:
region = "vrancea"

"vrancea"

In [12]:
side = 5

5

In [9]:
mapcoords= Dict("minLat"=>minimum(vrancea.Latitude),
            "maxLat"=>maximum(vrancea.Latitude),
            "minLon"=>minimum(vrancea.Longitude),
            "maxLon"=>maximum(vrancea.Longitude),
            "minDepth"=>minimum(vrancea.Depth),
            "maxDepth"=>maximum(vrancea.Depth),
            "minMag"=>minimum(vrancea.Magnitude),
            "maxMag"=>maximum(vrancea.Magnitude)
)

Dict{String, Float64} with 8 entries:
  "maxLon"   => 27.0
  "minMag"   => 0.6
  "minLon"   => 26.0
  "maxMag"   => 7.4
  "minLat"   => 45.2
  "maxLat"   => 46.0
  "maxDepth" => 196.0
  "minDepth" => 50.0

In [13]:
minLat=minimum(vrancea.Latitude)
maxLat=maximum(vrancea.Latitude)
minLon=minimum(vrancea.Longitude)
maxLon=maximum(vrancea.Longitude)
minDepth=minimum(vrancea.Depth)
maxDepth=maximum(vrancea.Depth)

196.0

In [18]:
if region=="vrancea" || region=="romania"
    longitudeInKm = 79
end

79

In [27]:
x = round((maxLat-minLat)*111 / side)

18.0

In [28]:
y = round((maxLon-minLon)*longitudeInKm / side)

16.0

In [29]:
z = round((maxDepth-minDepth) / side)

29.0

In [32]:
maxDim = maximum((x,y,z))

29.0

In [39]:
xLatitude = [floor(Int,((i-minLat)*x/(maxLat-minLat))+1) for i in vrancea.Latitude]

7890-element Vector{Int64}:
  8
 10
 11
 13
  1
 10
  4
 15
 18
  5
  ⋮
 12
 13
 10
 12
 12
  8
  8
 13
 11

In [40]:
yLongitude = [floor(Int,((i-minLon)*y/(maxLon-minLon))+1) for i in vrancea.Longitude]

7890-element Vector{Int64}:
  6
  9
  8
 13
 11
  4
  5
 11
  8
 17
  ⋮
  8
 11
  8
 10
 11
  9
  7
 10
 11

In [41]:
zDepth = [floor(Int,((i-minDepth)*y/(maxDepth-minDepth))+1) for i in vrancea.Depth]

7890-element Vector{Int64}:
 13
 12
 11
  5
 10
  8
  9
  7
  4
  7
  ⋮
 11
  5
 11
 10
  4
  7
  7
  4
 10

Int64[]

In [60]:
cubeIndex = zeros(Int64, 0)
for i = 1:length(xLatitude)
    append!(cubeIndex,maxDim*maxDim*(xLatitude[i]-1)+maxDim*(yLongitude[i]-1)+zDepth[i])
end
cubeIndex

7890-element Vector{Int64}:
  6045
  7813
  8624
 10445
   300
  7664
  2648
 12071
 14504
  3835
     ⋮
  9465
 10387
  7783
  9522
  9545
  6126
  6068
 10357
  8710

In [62]:
vrancea.xLatitude = xLatitude
vrancea.yLongitude = yLongitude
vrancea.zDepth = zDepth
vrancea.cubeIndex = cubeIndex

7890-element Vector{Int64}:
  6045
  7813
  8624
 10445
   300
  7664
  2648
 12071
 14504
  3835
     ⋮
  9465
 10387
  7783
  9522
  9545
  6126
  6068
 10357
  8710

In [63]:
vrancea

7890×9 DataFrame
  Row │ Datetime                 Latitude  Longitude  Depth    Magnitude  xLat ⋯
      │ DateTime                 Float64   Float64    Float64  Float64    Int6 ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ 1976-08-19T19:03:00.800   45.54      26.37      162.0        2.3       ⋯
    2 │ 1976-09-07T17:38:08.200   45.62      26.5       155.3        3.6
    3 │ 1976-10-01T17:50:43.200   45.68      26.49      146.0        6.0
    4 │ 1977-03-04T19:21:54.100   45.77      26.76       94.0        7.4
    5 │ 1977-03-04T21:21:01.100   45.22      26.65      141.0        3.0       ⋯
    6 │ 1977-03-05T02:35:22       45.63      26.19      121.3        3.0
    7 │ 1977-03-05T12:08:42       45.37      26.3       124.0        3.5
    8 │ 1977-03-06T13:27:06.300   45.83      26.63      112.3        2.6
  ⋮   │            ⋮                ⋮          ⋮         ⋮         ⋮           ⋱
 7884 │ 2022-12-17T05:42:58.120   45.641     26.487     143.8        4.1       ⋯
 7885 │ 2022-12-18T03:23:22.420   45.7235    26.6176    138.4        2.7
 7886 │ 2022-12-19T19:32:11.030   45.7157    26.6342     85.7        2.7
 7887 │ 2022-12-26T07:47:10.270   45.5403    26.5114    105.9        3.5
 7888 │ 2022-12-27T16:00:52.890   45.5211    26.4184    110.2        2.5       ⋯
 7889 │ 2022-12-28T07:38:54.270   45.7505    26.6086     85.2        2.9
 7890 │ 2022-12-29T02:06:28.320   45.6714    26.6291    134.0        2.8
                                                 4 columns and 7875 rows omitted

In [79]:
cubeLatitude=[round(minLat + (side/111)*(i-1/2), digits = 4) for i in xLatitude]
cubeLongitude=[round(minLon + (side/longitudeInKm)*(i-1/2), digits = 4) for i in yLongitude]
cubeDepth=[round(minDepth + (i-1/2), digits = 4) for i in zDepth]

7890-element Vector{Float64}:
 62.5
 61.5
 60.5
 54.5
 59.5
 57.5
 58.5
 56.5
 53.5
 56.5
  ⋮
 60.5
 54.5
 60.5
 59.5
 53.5
 56.5
 56.5
 53.5
 59.5

In [80]:
vrancea.cubeLatitude = cubeLatitude
vrancea.cubeLongitude = cubeLongitude
vrancea.cubeDepth = cubeDepth

7890-element Vector{Float64}:
 62.5
 61.5
 60.5
 54.5
 59.5
 57.5
 58.5
 56.5
 53.5
 56.5
  ⋮
 60.5
 54.5
 60.5
 59.5
 53.5
 56.5
 56.5
 53.5
 59.5

In [81]:
energyRelease=[10^(5.24 + 1.44*i) for i in vrancea.Magnitude]

7890-element Vector{Float64}:
 3.564511334262439e8
 2.6546055619755363e10
 7.585775750291852e13
 7.870457896951001e15
 3.6307805477010174e9
 3.6307805477010174e9
 1.9054607179632523e10
 9.638290236239705e8
 9.46237161365793e7
 3.6307805477010174e9
 ⋮
 1.342764961137864e9
 5.152286445817561e10
 1.393156802945298e11
 1.342764961137864e9
 1.342764961137864e9
 1.9054607179632523e10
 6.918309709189363e8
 2.6061535499988976e9
 1.8706821403658016e9

In [82]:
vrancea.energyRelease = energyRelease

7890-element Vector{Float64}:
 3.564511334262439e8
 2.6546055619755363e10
 7.585775750291852e13
 7.870457896951001e15
 3.6307805477010174e9
 3.6307805477010174e9
 1.9054607179632523e10
 9.638290236239705e8
 9.46237161365793e7
 3.6307805477010174e9
 ⋮
 1.342764961137864e9
 5.152286445817561e10
 1.393156802945298e11
 1.342764961137864e9
 1.342764961137864e9
 1.9054607179632523e10
 6.918309709189363e8
 2.6061535499988976e9
 1.8706821403658016e9

In [83]:
vrancea

7890×13 DataFrame
  Row │ Datetime                 Latitude  Longitude  Depth    Magnitude  xLat ⋯
      │ DateTime                 Float64   Float64    Float64  Float64    Int6 ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ 1976-08-19T19:03:00.800   45.54      26.37      162.0        2.3       ⋯
    2 │ 1976-09-07T17:38:08.200   45.62      26.5       155.3        3.6
    3 │ 1976-10-01T17:50:43.200   45.68      26.49      146.0        6.0
    4 │ 1977-03-04T19:21:54.100   45.77      26.76       94.0        7.4
    5 │ 1977-03-04T21:21:01.100   45.22      26.65      141.0        3.0       ⋯
    6 │ 1977-03-05T02:35:22       45.63      26.19      121.3        3.0
    7 │ 1977-03-05T12:08:42       45.37      26.3       124.0        3.5
    8 │ 1977-03-06T13:27:06.300   45.83      26.63      112.3        2.6
  ⋮   │            ⋮                ⋮          ⋮         ⋮         ⋮           ⋱
 7884 │ 2022-12-17T05:42:58.120   45.641     26.487     143.8        4.1       ⋯
 7885 │ 2022-12-18T03:23:22.420   45.7235    26.6176    138.4        2.7
 7886 │ 2022-12-19T19:32:11.030   45.7157    26.6342     85.7        2.7
 7887 │ 2022-12-26T07:47:10.270   45.5403    26.5114    105.9        3.5
 7888 │ 2022-12-27T16:00:52.890   45.5211    26.4184    110.2        2.5       ⋯
 7889 │ 2022-12-28T07:38:54.270   45.7505    26.6086     85.2        2.9
 7890 │ 2022-12-29T02:06:28.320   45.6714    26.6291    134.0        2.8
                                                 8 columns and 7875 rows omitted